source 'https://rubygems.org'

gem 'bcrypt', require: 'bcrypt'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'

gem 'pg'

gem 'zurb-foundation'
gem 'font-awesome-rails'
gem 'cocoon'
gem 'country_select'

gem "wash_out", "0.9.0"
gem 'qbxml', '~> 0.1.5'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'simple_form'

gem 'nokogiri'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'quickbooks-ruby', git: 'https://github.com/raksonibs/quickbooks-ruby.git', :branch => 'reports'

gem 'figaro'

gem 'oauth'
gem 'xeroizer'

gem 'oauth-plugin'

gem 'bourbon' # Should replace w/ autoprefixer: https://github.com/ai/autoprefixer-rails
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'spring'
  gem 'better_errors'
  gem 'letter_opener'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'rb-fsevent' # For mac – if using Linux add rb-inotify
  gem 'rspec-rails'
  gem 'timecop'

  # Debugging
  gem 'pry'
  gem 'pry-remote'
  gem 'binding_of_caller' # allows cmd-line in browser
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'shoulda-matchers'

  # Drivers
  gem 'capybara-webkit'
  gem 'selenium-webdriver'
  gem 'vcr'
end

