# A sample Guardfile
# More info at https://github.com/guard/guard#readme

require 'active_support/inflector'

guard :rspec, cmd: 'rspec --tag focus', run_all: { cmd: 'rspec --tag focus' }, failed_mode: :none, all_after_pass: false do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^app/(.+)\.(rb)$}) { "spec" }
  watch('config/routes.rb')
end